### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by rubyrosecraft** [June01/WFSAL-icmr21#2]
Could you help me with this problem?

```
#.Testing episode 17/1000
  \__.Dataset
       \__Name               : Thumos14reduced
       \__Class Num          : 5
       \__Picked_class       : ['HammerThrow', 'SoccerPenalty', 'JavelinThrow', 'FrisbeeCatch', 'VolleyballSpiking']
       \__Sample Num in all  : 5
       \__Batch  Num         : 1
       \__Test sample num    : 51
       \__samples.size()     : torch.Size([5, 13, 2048])
       \__sample.sum         : 17050.66015625
       \__samples idxs       : ['video_validation_0000316', 'video_validation_0000856', 'video_validation_0000414', 'video_validation_0000261', 'video_validation_0000983']
   \__Iterate test set
video_test_0000591
tensor([ 9223372035784278739,                    0,                    0,
        -4648419938486932129,  4356930959916527041])
['HammerThrow', 'SoccerPenalty', 'JavelinThrow', 'FrisbeeCatch', 'VolleyballSpiking']
Traceback (most recent call last):
  File "main.py", line 316, in <module>
    main()
  File "main.py", line 291, in main
    activityNet)
  File "/hd3/zhangyaru/WFSAL/test.py", line 137, in test
    key = picked_class[topkidx[j]]
IndexError: list index out of range
```

**Comment by June01** [comment]
Hi, I think you might start from checking the value of ```j``` and ```topkidx[j]``` to find clues.
